openapi: 3.0.3
info:
  title: Summer Camp Manager API
  version: 1.0.0
  description: API for managing summer camp operations including campers, events, rooms, and staff members

components:
  schemas:
    EntityMeta:
      $ref: "./schemas/EntityMeta.yaml"
    EntityCreationRequestMeta:
      $ref: "./schemas/EntityCreationRequestMeta.yaml"

    ListResponseBase:
      $ref: "./schemas/ListResponseBase.yaml"

    Camper:
      $ref: "./schemas/Camper.yaml"
    CamperCreationRequest:
      $ref: "./schemas/CamperCreationRequest.yaml"
    CamperUpdateRequest:
      $ref: "./schemas/CamperUpdateRequest.yaml"
    CampersListResponse:
      $ref: "./schemas/CampersListResponse.yaml"

    StaffMember:
      $ref: "./schemas/StaffMember.yaml"
    StaffMemberCreationRequest:
      $ref: "./schemas/StaffMemberCreationRequest.yaml"
    StaffMemberUpdateRequest:
      $ref: "./schemas/StaffMemberUpdateRequest.yaml"
    StaffMembersListResponse:
      $ref: "./schemas/StaffMembersListResponse.yaml"

    Role:
      $ref: "./schemas/Role.yaml"
    RoleCreationRequest:
      $ref: "./schemas/RoleCreationRequest.yaml"
    RoleUpdateRequest:
      $ref: "./schemas/RoleUpdateRequest.yaml"
    RolesListResponse:
      $ref: "./schemas/RolesListResponse.yaml"

    Area:
      $ref: "./schemas/Area.yaml"
    AreaCreationRequest:
      $ref: "./schemas/AreaCreationRequest.yaml"
    AreaUpdateRequest:
      $ref: "./schemas/AreaUpdateRequest.yaml"
    AreasListResponse:
      $ref: "./schemas/AreasListResponse.yaml"

    Location:
      $ref: "./schemas/Location.yaml"
    LocationCreationRequest:
      $ref: "./schemas/LocationCreationRequest.yaml"
    LocationUpdateRequest:
      $ref: "./schemas/LocationUpdateRequest.yaml"
    LocationsListResponse:
      $ref: "./schemas/LocationsListResponse.yaml"

    Program:
      $ref: "./schemas/Program.yaml"
    ProgramCreationRequest:
      $ref: "./schemas/ProgramCreationRequest.yaml"
    ProgramUpdateRequest:
      $ref: "./schemas/ProgramUpdateRequest.yaml"
    ProgramsListResponse:
      $ref: "./schemas/ProgramsListResponse.yaml"

    Activity:
      $ref: "./schemas/Activity.yaml"
    ActivityCreationRequest:
      $ref: "./schemas/ActivityCreationRequest.yaml"
    ActivityUpdateRequest:
      $ref: "./schemas/ActivityUpdateRequest.yaml"
    ActivitiesListResponse:
      $ref: "./schemas/ActivitiesListResponse.yaml"

    Color:
      $ref: "./schemas/Color.yaml"
    ColorCreationRequest:
      $ref: "./schemas/ColorCreationRequest.yaml"
    ColorUpdateRequest:
      $ref: "./schemas/ColorUpdateRequest.yaml"
    ColorsListResponse:
      $ref: "./schemas/ColorsListResponse.yaml"

    Certification:
      $ref: "./schemas/Certification.yaml"
    CertificationCreationRequest:
      $ref: "./schemas/CertificationCreationRequest.yaml"
    CertificationUpdateRequest:
      $ref: "./schemas/CertificationUpdateRequest.yaml"
    CertificationsListResponse:
      $ref: "./schemas/CertificationsListResponse.yaml"

    HousingRoom:
      $ref: "./schemas/HousingRoom.yaml"
    HousingRoomCreationRequest:
      $ref: "./schemas/HousingRoomCreationRequest.yaml"
    HousingRoomUpdateRequest:
      $ref: "./schemas/HousingRoomUpdateRequest.yaml"
    HousingRoomsListResponse:
      $ref: "./schemas/HousingRoomsListResponse.yaml"

    Session:
      $ref: "./schemas/Session.yaml"
    SessionCreationRequest:
      $ref: "./schemas/SessionCreationRequest.yaml"
    SessionUpdateRequest:
      $ref: "./schemas/SessionUpdateRequest.yaml"
    SessionsListResponse:
      $ref: "./schemas/SessionsListResponse.yaml"

    Group:
      $ref: "./schemas/Group.yaml"
    GroupCreationRequest:
      $ref: "./schemas/GroupCreationRequest.yaml"
    GroupUpdateRequest:
      $ref: "./schemas/GroupUpdateRequest.yaml"
    GroupsListResponse:
      $ref: "./schemas/GroupsListResponse.yaml"

    Event:
      $ref: "./schemas/Event.yaml"
    EventCreationRequest:
      $ref: "./schemas/EventCreationRequest.yaml"
    EventUpdateRequest:
      $ref: "./schemas/EventUpdateRequest.yaml"
    EventsListResponse:
      $ref: "./schemas/EventsListResponse.yaml"

    Camp:
      $ref: "./schemas/Camp.yaml"
    CampCreationRequest:
      $ref: "./schemas/CampCreationRequest.yaml"
    CampUpdateRequest:
      $ref: "./schemas/CampUpdateRequest.yaml"

    DurationPreset:
      $ref: "./schemas/DurationPreset.yaml"
    DurationPresetCreationRequest:
      $ref: "./schemas/DurationPresetCreationRequest.yaml"
    DurationPresetUpdateRequest:
      $ref: "./schemas/DurationPresetUpdateRequest.yaml"

paths:
  /sessions:
    $ref: "./paths/Sessions.yaml"
  /sessions/{id}:
    $ref: "./paths/SessionsById.yaml"

  /campers:
    $ref: "./paths/Campers.yaml"
  /campers/{id}:
    $ref: "./paths/CampersById.yaml"

  /staff-members:
    $ref: "./paths/StaffMembers.yaml"
  /staff-members/{id}:
    $ref: "./paths/StaffMembersById.yaml"

  /areas:
    $ref: "./paths/Areas.yaml"
  /areas/{id}:
    $ref: "./paths/AreasById.yaml"

  /locations:
    $ref: "./paths/Locations.yaml"
  /locations/{id}:
    $ref: "./paths/LocationsById.yaml"

  /programs:
    $ref: "./paths/Programs.yaml"
  /programs/{id}:
    $ref: "./paths/ProgramsById.yaml"

  /activities:
    $ref: "./paths/Activities.yaml"
  /activities/{id}:
    $ref: "./paths/ActivitiesById.yaml"

  /colors:
    $ref: "./paths/Colors.yaml"
  /colors/{id}:
    $ref: "./paths/ColorsById.yaml"

  /roles:
    $ref: "./paths/Roles.yaml"
  /roles/{id}:
    $ref: "./paths/RolesById.yaml"

  /certifications:
    $ref: "./paths/Certifications.yaml"
  /certifications/{id}:
    $ref: "./paths/CertificationsById.yaml"

  /housing-rooms:
    $ref: "./paths/HousingRooms.yaml"
  /housing-rooms/{id}:
    $ref: "./paths/HousingRoomsById.yaml"

  /groups:
    $ref: "./paths/Groups.yaml"
  /groups/{id}:
    $ref: "./paths/GroupsById.yaml"

  /events:
    $ref: "./paths/Events.yaml"
  /events/{id}:
    $ref: "./paths/EventsById.yaml"

  /camps:
    $ref: "./paths/Camps.yaml"
  /camps/{id}:
    $ref: "./paths/CampsById.yaml"

  /tenants:
    $ref: "./paths/Tenants.yaml"
  /tenants/{id}:
    $ref: "./paths/TenantsById.yaml"
